[package]
name = "four_mb"
version = "0.1.0"
authors = ["Emil Wasilewski <emil.wasilewski@brickmakers.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
ggez = "0.5.1"
ncollide2d = "0.30.0"
rapier2d = "0.9.2"
nalgebra = "0.27.0"
